import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import aboutData from '../public/about-data'
import Card from '../components/card'
import { FontAwesomeIcon } from '@fortawesome/react-fontawesome'
import {
    faLinkedin,
    faGithub
  } from '@fortawesome/free-brands-svg-icons'

export async function getStaticProps() {
    return {
        props: {
            aboutData
        }
    }
}


export default function About(props) {
    return (
        <div className={styles.container}>
            <Head>
                <title>About Me</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           <main className={styles.main}>
                <div className={styles.menu}>
                    <div className={styles.header}>
                        <Image
                            priority
                            src='/spiderman.jpg'
                            height={200}
                            width={200}
                            alt='spiderman picture'
                            className={styles.image}
                        />
                        <h1 className={styles.title}>Johnathan Hoyt</h1>
                        <h2>Web Developer</h2>
                    </div>
                    <ul className={styles.navigation}>
                        <Link href='/'>
                            <a className={styles.links}>Home</a>
                        </Link>
                        <Link href='/journey'>
                            <a className={styles.links}>My Journey</a>
                        </Link>
                        <Link href='/hobbies'>
                            <a className={styles.links}> My Hobbies</a>
                        </Link>
                        <Link href='https://www.linkedin.com/in/johnathan-hoyt-177508146/'>
                            <FontAwesomeIcon icon={faLinkedin} style={{width: '40px'}} />
                        </Link>
                        <Link href='https://github.com/jhoyt200931'>
                            <FontAwesomeIcon icon={faGithub} style={{width: '40px'}}/>
                        </Link>   
                    </ul>
                </div>
                <div className={styles.content}>
                    <h1 className={styles.pageTitle}>About Me</h1>
                    {props.aboutData.map((snippet) => {
                    return <Card props={snippet}/>
                    })}
                </div>
           </main>
           <footer className={styles.footer}>
                <Link href='https://www.linkedin.com/in/johnathan-hoyt-177508146/'>
                    <FontAwesomeIcon icon={faLinkedin} style={{width: '50px'}} />
                </Link>
                <Link href='https://github.com/jhoyt200931'>
                    <FontAwesomeIcon icon={faGithub} style={{width: '50px', margin: '10px'}}/>
                </Link>
           </footer>
        </div>
    )
}