import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function About() {
    return (
        <div className={styles.container}>
            <Head>
                <title>About Me</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
           
            <div className={styles.header}>
                <Image
                    priority
                    src='/spiderman.jpg'
                    height={200}
                    width={200}
                    alt='spiderman picture'
                    className={styles.image}
                />
                <h1 className={styles.title}>About Me</h1>
            </div>
            <div>
                <Link href='/'>
                    <a className={styles.links}>Home</a>
                </Link>
                <Link href='/hobbies'>
                    <a className={styles.links}> My Hobbies</a>
                </Link>   
            </div>
            <p className={styles.description}>This is the About Me page where I will go into a little detail about my background:</p>
            <p className={styles.description}>
                I am currently 25 years of age and I was born and raised in Central New York. I'm the 2nd youngest of 4 children and we grew up in a home without much money, but we always got by. I am a massive Star Wars and comic book fan. My favorite characters are Batman, Spider-Man, Deadpool and The Joker. My love for Star Wars and comic books started at the age of 3 when my father brought home the boxed set of the Star Wars Original Trilogy. According to his stories, he wanted to watch a Star Wars marathon and from the moment he put the first movie in, I sat there and did not move throughout the entire trilogy.
            </p>
            <p className={styles.description}>
                I also got my love of technology from my father who went to ITT Technical Institute for a networking degree. When I was a child, my father would always be working on computers and I would always be up behind him asking what the parts were and why they made the computer work.
            </p>
            <p className={styles.description}>
                As I grew older, I started to take electronic devices apart, starting with my CD player that my parents had gotten me a few years before(that one did not turn out well). My interest in technology has persisted all throughout my life. Though at times it did take a backseat to other pursuits for a while.
            </p>
            <p className={styles.description}>    
                Getting into high school, I started to get more into sports and become more physically active than I had typically been to that point. My main sport was football, and it still is my favorite to this day.
            </p>   
            <p className={styles.description}>
                I turned out to be quite the football player, to the point where the coach kept telling my that I could be scouted by college teams. And at the time, that did seem exciting to me, but it was not my true goal.
            </p>
            <p className={styles.description}>
                My true goal was to get a job directly out of high school so that I could start to support myself and ease the burden on my family. I succeeded in this goal and moved out of my parents home at the age of 18. I started off in the fast food industry like so many others and eventually found myself doing customer service for AT&T and then later a furniture company.
            </p>
            <p className={styles.description}>
                It was at this furniture company that my love of technology came back to the forefront for me and started to drive my pursuit to become a developer. Now I'm attempting to break into the tech industry to improve my life and to work in an area that I've always been interested in.
            </p>
            <footer className={styles.footer}>
            </footer>
        </div>
    )
}