import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'
import hobbiesData from '../public/hobbies-data'
import Card from '../components/card'

export async function getStaticProps() {
    const data = hobbiesData
    return {
        props: {
            data
        }
    }
}

export default function Hobbies(props) {
    return (
        <div className={styles.container}>
            <Head>
                <title>Hobbies</title>
                <meta name="description" content="Generated by create next app" />
                <link rel="icon" href="/favicon.ico" />
            </Head>
            <div className={styles.header}>
                <Image 
                    priority
                    src='/deadpool.jpg'
                    height={200}
                    width={200}
                    className={styles.image}
                />
                <h1 className={styles.title}>My hobbies</h1>
            </div>
            <div>
            <Link href='/'>
                <a className={styles.links}>Home</a>
            </Link>
            <Link href='/journey'>
                <a className={styles.links}>My Journey</a>
            </Link>
            <Link href='/about'>
                <a className={styles.links}>About Me</a>
            </Link>
            </div>
            {props.data.map((hobby) => {
               return <Card props={hobby}/>
            })}
            <footer className={styles.footer}>
            </footer>
        </div>
    )
}
