import Head from 'next/head'
import Image from 'next/image'
import styles from '../styles/Home.module.css'
import Link from 'next/link'

export default function Home() {
  return (
    <div className={styles.container}>
      <Head>
        <title>John's profile</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <div className={styles.header}>
          <Image
            className={styles.image}
            priority
            src='/batman.jpg'
            height={200}
            width={200}
            alt='batman picture'
          />
          <h1 className={styles.title}>
            Johnathan Hoyt
          </h1>
        </div>

        <ul>
          <Link href='/about'>
            <a className={styles.links}>About Me</a>
          </Link>
          <Link href='/hobbies'>
            <a className={styles.links}>My Hobbies</a>
          </Link>
        </ul>

        <p className={styles.description}>
          Hello, my name is Johnathan and this is a small site containing information about me and my journey to become a developer.
        </p>

        <p className={styles.description}>
          Let's start with a brief account of my journey into development:
          <br />
          My journey first started 3.5 years ago while I was still working customer service for a furniture company based in the state of New York. I was starting to get bored with this line of work and wanted to get into something more technical and challenging, so I started teaching myself how to code in my spare time.
          <br />
          Eventually, I got far enough into JavaScript to start on React. It was at this point that I realized that teacing myself was not going to cut it and I decided that I needed a more formal education on the matter.
          <br />
          After this, I was biding my time, waiting for the right opportunity to come along. After 2.5 years, that opportunity came in the form of Lambda School. Once I had heard of Lambda School, I decided it was time and I signed up. What followed was probably the most challenging, rewarding and fun educational experience I have ever endured.
          <br />
          Throughout my time at Lambda School, I learned HTML5, CSS3(and some preprocessors), vanilla JavaScript, React.js, Redux, Node.js and Python3. The road was not easy, but I learned so much and my skillset grew by leaps and bounds. Bringing my to today, in the job hunt in a new, more technical field.
        </p>
      </main>

      <footer className={styles.footer}>
      </footer>
    </div>
  )
}
